### ISSUE TITLE
Segfault group.descriptionChanged

### ISSUE THREAD

**Issue by jvanveen** [jech/galene#102]
Just updated Galene to test with the group public list updates (https://github.com/jech/galene/commit/06f2ecec16e96e95105d8b3230741373ceffbaaf) and encountered this error:

```
galene    | panic: runtime error: invalid memory address or nil pointer dereference
galene    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x807196]
galene    | 
galene    | goroutine 399 [running]:
galene    | github.com/jech/galene/group.descriptionChanged(0xc000310c15, 0x3, 0x0, 0x0)
galene    |     /go/pkg/mod/github.com/jech/galene@v0.0.0-20210822143618-06f2ecec16e9/group/group.go:907 +0x76
galene    | github.com/jech/galene/group.Update()
galene    |     /go/pkg/mod/github.com/jech/galene@v0.0.0-20210822143618-06f2ecec16e9/group/group.go:1032 +0x185
galene    | created by main.main
galene    |     /go/pkg/mod/github.com/jech/galene@v0.0.0-20210822143618-06f2ecec16e9/galene.go:147 +0xd45
galene exited with code 2
```
Not sure at what point it happened...

**Comment by jech** [comment]
Fixed in 475e36d, thanks.
